spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
##以/api/a/**请求全部转发到ribbon服务中，以/api/b/**全部转发到feign服务##
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign